// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RedeSocialUniversidade.Infra;

#nullable disable

namespace RedeSocialUniversidade.Infra.Migrations
{
    [DbContext(typeof(SqlContext))]
    [Migration("20250331181111_Usuario")]
    partial class Usuario
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RedeSocialUniversidade.Domain.Entities.Seguidor", b =>
                {
                    b.Property<int>("UsuarioSeguidoId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioSeguidorId")
                        .HasColumnType("int");

                    b.HasKey("UsuarioSeguidoId", "UsuarioSeguidorId");

                    b.HasIndex("UsuarioSeguidorId");

                    b.ToTable("Seguidor");
                });

            modelBuilder.Entity("RedeSocialUniversidade.Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Curso")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("RedeSocialUniversidade.Domain.Entities.Seguidor", b =>
                {
                    b.HasOne("RedeSocialUniversidade.Domain.Entities.Usuario", "UsuarioSeguido")
                        .WithMany("Seguidores")
                        .HasForeignKey("UsuarioSeguidoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RedeSocialUniversidade.Domain.Entities.Usuario", "UsuarioSeguidor")
                        .WithMany()
                        .HasForeignKey("UsuarioSeguidorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("UsuarioSeguido");

                    b.Navigation("UsuarioSeguidor");
                });

            modelBuilder.Entity("RedeSocialUniversidade.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("Seguidores");
                });
#pragma warning restore 612, 618
        }
    }
}
